name: CI

on:
    pull_request:
        branches: [main, develop]

jobs:
    ci:
        name: Lint and Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js and cache Yarn
              uses: actions/setup-node@v4
              with:
                  node-version: "latest"
                  cache: "yarn"

            - name: Get Playwright version
              id: playwright-version
              run: echo "version=$(node -e "console.log(require('./package.json').devDependencies.playwright)")" >> $GITHUB_OUTPUT

            - name: Cache Playwright browsers
              uses: actions/cache@v4
              id: playwright-cache
              with:
                  path: ~/.cache/ms-playwright
                  key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Install Playwright Chromium
              if: steps.playwright-cache.outputs.cache-hit != 'true'
              run: yarn playwright install chromium --with-deps

            - name: Install Playwright deps
              if: steps.playwright-cache.outputs.cache-hit == 'true'
              run: yarn playwright install-deps chromium

            - name: Run linting
              run: yarn run lint

            - name: Run unit tests
              run: yarn run test:unit

            - name: Run storybook tests
              run: yarn run test:storybook
